"""empty message

Revision ID: 6490fa92f15f
Revises: 3fb6d4fca603
Create Date: 2024-01-13 17:10:06.689000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6490fa92f15f'
down_revision = '3fb6d4fca603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ongs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aprobado', sa.Boolean(), nullable=False))
        batch_op.drop_column('esta_aprobado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ongs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('esta_aprobado', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('aprobado')

    # ### end Alembic commands ###
