"""empty message

Revision ID: a43f68e7e6a1
Revises: 6490fa92f15f
Create Date: 2024-01-25 18:07:38.307967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a43f68e7e6a1'
down_revision = '6490fa92f15f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ongs', schema=None) as batch_op:
        batch_op.alter_column('aprobado',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['aprobado'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ongs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('aprobado',
               existing_type=sa.String(length=120),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###
